name: Docs

on:
  push:
    paths:
      - 'doc/*'
    branches:
      - '4.1'
  pull_request:
    paths:
      - 'doc/*'
    branches:
      - '4.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
        working-directory: 'doc'
      - run: npm run build:docs
        working-directory: 'doc'
      # REMIND: lint:links task is unreliable, enable again when we found a solution
      #- run: npm run lint:links
      #  working-directory: 'doc'
