name: JVM CI with Maven

on:
  push:
    branches:
      - '5.0'
  pull_request:
    branches:
      - '5.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala-version: [2.12, 2.13]
        spark-version: ["3"]
        neo4j-version: ["4.4", "5"]
    name: Build with Scala ${{ matrix.scala-version }}, Spark ${{ matrix.spark-version }} and Neo4j ${{ matrix.neo4j-version }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !(matrix.spark-version == 3 && matrix.scala-version == 2.11) && !(matrix.spark-version == 2.4 && matrix.scala-version == 2.13) }}
      - name: Set up JDK 8
        if: ${{ !(matrix.spark-version == 3 && matrix.scala-version == 2.11) && !(matrix.spark-version == 2.4 && matrix.scala-version == 2.13) }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        if: ${{ !(matrix.spark-version == 3 && matrix.scala-version == 2.11) && !(matrix.spark-version == 2.4 && matrix.scala-version == 2.13) }}
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        if: ${{ !(matrix.spark-version == 3 && matrix.scala-version == 2.11) && !(matrix.spark-version == 2.4 && matrix.scala-version == 2.13) }}
        env:
          CI: true
        run: ./mvnw clean verify -Pscala-${{ matrix.scala-version }} -Pspark-${{ matrix.spark-version }} -Pneo4j-${{ matrix.neo4j-version }} --no-transfer-progress
