name: Trigger Publish

on:
  push:
    paths:
      - 'doc/docs'
    branches:
      - '4.1'

jobs:
  trigger_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Developer Event
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.BUILD_ACCESS_TOKEN }}
          repository: neo4j-documentation/docs-refresh
          event-type: spark-connector
