name: Python Tests for Spark 2.4

on:
  push:
    branches:
      - '4.0'
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc
          pip install pyspark==2.4.5 "testcontainers[neo4j]"
      - name: Build artifact for Scala 2.11
        run: |
          ./mvnw clean package -DskipTests -P spark-2.4 -P scala-2.11 --no-transfer-progress
      - name: Run tests for Scala 2.11
        run: |
          cd ./scripts/python
          python test_spark.py "2.4" "2.11"